apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: price-search-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: price-search
    spec:
      containers:
      - image: oblacki/price-search:261217v1
        name: price-search
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
        livenessProbe:
          httpGet:
            path: /health
            port: 8083
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8083
          name: server
          protocol: TCP